---
name: nightmayr-qtwebengine-6-3-1-2204
version: 6.3.1
base: core22
summary: QtWebengine to be used as a stage snap by Qt content snap
description: |
 This snap contains QtWebengine to be staged in the Qt SDK and content snaps.
confinement: strict
grade: stable
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
parts:
    qtwebengine:
        source: git://code.qt.io/qt/qtwebengine.git
        source-tag: v$SNAPCRAFT_PROJECT_VERSION
        plugin: cmake
        cmake-generator: Ninja
        build-environment:
        - LD_LIBRARY_PATH: $CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
        - PKG_CONFIG_PATH: /snap/nightmayr-qt-6-3-1-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET/pkgconfig:${PKG_CONFIG_PATH:+:PKG_CONFIG_PATH}
        override-build: |
            # Setting number of build jobs to a safe number to prevent running out of memory during QtWebengine build
            memtotal=$(cat /proc/meminfo | awk '{print $2}' | head -n1)
            roundedmem=$(python3 -c "print(round($memtotal/1024000.0))")
            maxcoresformem=$(python3 -c "print(max(1, int(($roundedmem / 2)-2)))")
            numcoreslow=$(python3 -c "print(min($maxcoresformem, $CRAFT_PARALLEL_BUILD_COUNT))")
            export NINJAFLAGS=-j$numcoreslow
            export NINJAJOBS=-j$numcoreslow
            cmake $CRAFT_PART_SRC -G Ninja -DCMAKE_LIBRARY_PATH=$CRAFT_ARCH_TRIPLET \
              -DCMAKE_INSTALL_PREFIX=$CRAFT_PART_INSTALL/usr \
              -DCMAKE_INSTALL_LIBDIR=lib/$CRAFT_ARCH_TRIPLET \
              -DCMAKE_INSTALL_RUNSTATEDIR=/run \
              -DCMAKE_INSTALL_LOCALSTATEDIR=/var \
              -DCMAKE_INSTALL_SYSCONFDIR=/etc \
              -DFEATURE_webengine_system_ffmpeg=ON \
              -DFEATURE_webengine_system_icu=ON \
              -DFEATURE_webengine_system_libevent=ON \
              -DFEATURE_qtpdf_build=ON \
              -DFEATURE_qtpdf_widgets_build=ON \
              -DFEATURE_qtpdf_quick_build=ON \
              -DFEATURE_webengine_proprietary_codecs=ON \
              -DCMAKE_FIND_ROOT_PATH=/usr\;/root/stage\;/snap/nightmayr-qt-6-3-1-2204-sdk/current \
              --log-level=STATUS
            cmake --build . -- -j$numcoreslow
            cmake --build . --target install
            if [ $CRAFT_TARGET_ARCH = "armhf" ]; then
              execstack --clear-execstack $CRAFT_PART_INSTALL/usr/lib/$CRAFT_ARCH_TRIPLET/libQt6WebEngineCore.so.*
            fi
        build-snaps:
        - cmake
        - nightmayr-qt-6-3-1-2204-sdk/latest/candidate
        build-packages:
        - execstack
        - python3
        - flex
        - gperf
        - bison
        - node-less
        - libnss3-dev
        - libxkbcommon-x11-dev
        - libxcb-render0-dev
        - libxcb-image0-dev
        - libxcb-shape0-dev
        - libxcb-sync-dev
        - libxcb-render-util0-dev
        - libxcb1-dev
        - libxcb-xfixes0-dev
        - libxcb-icccm4-dev
        - libxcb-keysyms1-dev
        - libxcb-shm0-dev
        - libxrender-dev
        - libxcb-xinerama0
        - libdrm-dev
        - libxkbfile-dev
        - libxtst-dev
        - libxdamage-dev
        - libpulse-dev
        - libasound2-dev
        - libaudio-dev
        - libcups2-dev
        - libdbus-1-dev
        - libfreetype6-dev
        - libgl1-mesa-dev
        - libglib2.0-dev
        - libegl1-mesa-dev
        - libglu1-mesa-dev
        - libice-dev
        - libjpeg-dev
        - libmng-dev
        - libpng-dev
        - libsm-dev
        - libsqlite3-dev
        - libssl-dev
        - libtiff5-dev
        - libx11-dev
        - libx11-xcb-dev
        - libxcursor-dev
        - libxext-dev
        - libxft-dev
        - libxi-dev
        - libxinerama-dev
        - libxmu-dev
        - libxrandr-dev
        - libxt-dev
        - libxv-dev
        - zlib1g-dev
        - libedit-dev
        - libwayland-dev
        - libwayland-egl1-mesa
        - libmtdev-dev
        - libudev-dev
        - libxkbcommon-dev
        - libxcomposite-dev
        - libgraphite2-dev
        - libvulkan-dev
        - python3-html5lib
        - libicu-dev
        - libevent-dev
        - libwebp-dev
        - libopus-dev
        - libre2-dev
        - libxslt1-dev
        - libvpx-dev
        - libharfbuzz-dev
        - libsnappy-dev
        - libpci-dev
        - libxml2-dev
        - libxss-dev
        - libminizip-dev
        - libxshmfence-dev
